#!/usr/bin/env bash

MSO_FILE_TYPES='\.ppt$\|\.pptx$\|\.doc$\|\.docx$\|\.xsl$\|\.xslx$' 

IFS_SAVE=$IFS

export IFS=`echo -ne '\0'`

ALL_FILES=$( cat )
FILES=$( echo $ALL_FILES | grep $MSO_FILE_TYPES )
echo $ALL_FILES | grep -v $MSO_FILE_TYPES

libreoffice --headless --invisible --convert-to pdf $FILES 2>&1 >/dev/null

for F in $FILES
do
  OF=$( echo $F | sed -e "s/$MSO_FILE_TYPES/.pdf/" )
  mv "$OF" "$F.pdf"
  echo "$F.pdf"
done


export IFS=$IFS_SAVE
