#!/usr/bin/env bash

export IFS=$'\n'

TIMEOUT=10
TRIES=3
ACCEPT_CONFIG='/etc/get-slides.d/file.accept'
if [[ -a $ACCEPT_CONFIG ]]
then
  ACCEPT_CONFIG=$( < $ACCEPT_CONFIG )
fi

if [[ "XX$ACCEPT_FILE_TYPE" = "XX" ]]
then
  ACCEPT_FILE_TYPE='*.pdf,*.ppt,*.pptx,*.doc,*.docx,*.ps,*.xsl,*.xslx' 
fi

ACCEPT_FILE_GREP=$( echo "$ACCEPT_FILE_TYPE" | sed -e 's/,/\\|/g' | sed -e 's/\*\./.*\\./g' )

URL=$1
shift

{ wget -e robots=off --timeout=$TIMEOUT --tries=$TRIES \
    -nv \
    -r -H -nd -N \
    -R'*.html,*.htm' -A"$ACCEPT_FILE_TYPE" "$@" "$URL" 2>&1 ; \
    if [[ $? -ne 0 ]]
    then
      echo "Network Error On {$URL}" 1>&2
    fi ; \
  } |\
  grep -o -- "-> \"\($ACCEPT_FILE_GREP\)\"" |\
  sed -e "s/-> \"\($ACCEPT_FILE_GREP\)\"/\1/"

